name: nokufind
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  async: ^2.11.0
  characters: ^1.3.0
  crypto: ^3.0.3
  dio: ^5.4.3+1
  dio_http2_adapter: ^2.5.2
  dio_smart_retry: ^6.0.0
  executor: ^2.2.3
  html: ^0.15.4
  html2md: ^1.3.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  trotter: ^2.2.0
  xml: ^6.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
